program: main.py
name: "find batchsize"
project: "CV_project1_tune"
description: "Base on Resnet50"
method: grid
parameters:
  batch_size:
    value: 100
  epochs:
    value: 50
  lr:
    value: 0.05
  wd:
    value: 0
