program: main.py
name: "use_cosine_scheduler"
method: grid
parameters:
  batch_size:
    value: [16, 32, 64]
  epochs:
    value: 50
  lr:
    values: 0.5
  wd:
    value: 0
  scheduler:
#    value: "cosine"
    value: "constant"
