program: main.py
name: "Using Adam"
project: "CV_project1_tune"
description: "Base on Resnet50"
method: grid
metric:
  name: val_metric
  goal: maximize
parameters:
  batch_size:
    value: 100
  epochs:
    value: 30
  lr:
    values: [0.001, 0.005, 0.01]
  wd:
    value: 0
  optimizer:
    value: "Adam"
  momentum:
    value: 0
