program: main.py
name: "use_cosine_scheduler"
method: grid
parameters:
  batch_size:
    value: 100
  epochs:
    value: 50
  lr:
    values: [1, 0.5, 0.25, 0.1, 0.05]
  wd:
    value: 0.0005
  scheduler:
#    value: "cosine"
    value: "constant"
