program: main.py
name: "select momentum"
project: "CV_project1_tune"
description: "Base on Resnet50"
method: grid
parameters:
  batch_size:
    value: 100
  epochs:
    value: 30
  lr:
    value: 0.05
  wd:
    values: [0.001, 0.0005]
  optimizer:
    value: "SGD"
  momentum:
    values: [0.5, 0.1]
