program: main.py
name: "Using SGD! with some different Wd"
project: "CV_project1_tune"
description: "Base on Resnet50"
method: grid
metric:
  name: val_metric
  goal: maximize
parameters:
  batch_size:
    value: 100
  epochs:
    value: 30
  lr:
    value: 0.05
  wd:
    values: [0.002, 0.0025]
  optimizer:
    value: "SGD"
  momentum:
    value: 0.9
  weight:
    value: True

