wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.10.9
    start_time: 1679123236.070011
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      - 37
      4: 3.10.9
      5: 0.13.10
      8:
      - 1
      - 2
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.05
wd:
  desc: null
  value: 0.0005
